version: '3.0'
services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: my-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx:rw
      - ./www:/usr/share/nginx/html:rw
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - front
      - backend

  mysql:
    image: mysql:5.7.26
    container_name: my-mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data/:/var/lib/mysql/
      - ./mysql/conf.d/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:rw
    environment:
      MYSQL_ROOT_PASSWORD : root

  redis:
    container_name: my-redis
    restart: always
    image: redis:5.0.9
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:rw
      - ./redis/data:/data:rw
      - ./redis/logs:/var/log/:rw

  my-cpms:
    image: cpms:latest
    container_name: cpms
    restart: always
    ports:
      - 8001:8001
    volumes:
      - ./java/cpms/logs:/applogs

networks:
  front:
  backend:
